### ISSUE TITLE
Несколько советов по коду

### ISSUE THREAD

**Issue by zhebrak** [tasktrack/Python.Tasks#1]
Мой PEP8 Linter ругается на всякие мелочи вроде [инлайн-комментариев](https://www.python.org/dev/peps/pep-0008/#comments). Также есть вопросы к именованию переменных
```python
def findMatch(GameList, Team1, Team2):
    for e in GameList:
```
должно быть
```python
def find_match(game_list, team1, team2):
    for game in game_list:
```
переменные и функции в lower-case с нижним подчеркиванием.

В остальном все отлично, хорошее решение!

**Comment by StealthTech** [comment]
Большое спасибо! Это всё влияние c# сказывается: по старой памяти вылезает camelcase. Придется отучаться ;)

**Comment by zhebrak** [comment]
Да, я помню, привыкайте :)

_Исправлять этот код, разумеется, не надо, комментарии на будущее._
